### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by robmarkcole** [aws-samples/aws-machine-learning-university-accelerated-cv#18]
from main readme: `Final Project: Practice working with a "real-world" computer vision dataset for the final project. Final project dataset is in the data/final_project_dataset folder. For more details on the final project, check out this notebook.`

https://github.com/aws-samples/aws-machine-learning-university-accelerated-cv/blob/master/notebooks/MLA-CV-Lecture1-Final-Project.ipynb

**Comment by cemsaz** [comment]
thanks @robmarkcole We will send a fix for this quickly.

**Comment by cemsaz** [comment]
It is corrected with this [PR](https://github.com/aws-samples/aws-machine-learning-university-accelerated-cv/pull/19). Thanks.
